---
deployment:
  tasks:
    - export DEPLOYPATH=/home/messeng1/vue.messenger.com.ng/
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R img $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp * $DEPLOYPATH
